export * from './effect.js'
export * from './grammar-hint.js'
export * from './source.js'
export * from './core/hypercomb.web.js'
export * from './core/hypercomb.js'
export * from './core/signature.service.js'
export * from './core/signature-predicate.js'
export * from './core/signature-store.js'
export * from './core/content-cipher.js'
export * from './host.types.js'
export * from './core/pool-registry.js'
export * from './core/level-roster.js'
export * from './core/edge-registry.js'
export * from './core/life-primitive.js'
export * from './core/canonical-reference.js'
export * from './core/packed-store-flag.js'
export * from './core/group-signature.js'
export * from './dcp-message.js'
export * from './bee.base.js'
export * from './worker.base.js'
export * from './drone.base.js'
export * from './queen.base.js'
export * from './payload-canonical.js'
export * from './core/computation-receipt.js'
export * from './provider-link.js'
export * from './core/bee-resolver.js'
export * from './ioc/ioc.js'
export * from './ioc/service-key.js'
export { EffectBus, type EffectHandler } from './effect-bus.js'
export * from './keymap.js'
export * from './keymap-format.js'
export * from './platform.js'
export { normalizeCell, isValidCell } from './cell.js'
export * from './i18n.types.js'
export * from './command-object.js'
export * from './icon-pick.types.js'
export * from './usage.types.js'
export * from './theme.types.js'
export * from './icon-ref.js'
export * from './tile-content-renderer.js'
export * from './confirm.js'
export * from './substrate.types.js'
export * from './pointer-gesture-consumer.js'
export * from './portable-tile.js'
export * from './core/client-identity.js'
export * from './core/assistant-chat-config.js'
export * from './core/local-claude-bridge.js'
export * from './core/llm-keys.js'
export * from './core/secret-words/index.js'
export * from './core/revision-name.js'
export * from './core/behaviour-call.js'

// The PANEL KIT — the docked tool-window model, moved out of the Angular shell
// (2026-09-01) so a behaviour can build its own chrome. Framework-free by
// construction: a module may only import from core, and the shim cannot load
// Angular at all. `docked-panel.js` is the primitive itself; the rest is the
// model it drives (lanes, groups, settings rows, sessions, breakpoints).
export * from './core/panels/breakpoints.js'
export * from './core/panels/window-session.js'
export * from './core/panels/window-rule.js'
export * from './core/panels/dock-lanes.js'
export * from './core/panels/panel-groups.js'
export * from './core/panels/panel-settings.js'
export * from './core/panels/tool-windows.js'
export * from './core/panels/docked-panel.js'
