// hypercomb-core/src/library.ts
//
// THE LIBRARY — everything core exports beyond the processor: pools, heads,
// broods, grammar, the panel kit, word lists. Modules import it through
// `@hypercomb/core` as before; the minimal install resolves these bytes by
// signature instead of shipping them.

export * from './effect.js'
export * from './grammar-hint.js'
export * from './source.js'
export * from './core/signature-predicate.js'
export * from './core/signature-store.js'
export * from './core/content-cipher.js'
export * from './host.types.js'
export * from './install.types.js'
export * from './attestation.types.js'
export * from './core/pool-registry.js'
export * from './core/eggs.js'
export * from './core/module-sections.js'
export * from './core/brood.js'
export * from './core/code-reach.js'
export * from './core/brood-rules.js'
export * from './core/lineage-key.js'
export * from './core/molecule-address.js'
export * from './core/pool-kinds.js'
export * from './core/reference-rule.js'
export * from './core/level-roster.js'
export * from './core/edge-registry.js'
export * from './core/directory-safety.js'
export * from './core/format-version.js'
export * from './core/head-claim.js'
export * from './core/head-map.js'
export * from './core/vocabulary-claim.js'
export * from './core/life-primitive.js'
export * from './core/canonical-reference.js'
export * from './core/packed-store-flag.js'
export * from './core/group-signature.js'
export * from './dcp-message.js'
export * from './payload-canonical.js'
export * from './core/computation-receipt.js'
export * from './provider-link.js'
export * from './core/machine-grammar.js'
export * from './core/machine-admission.js'
export * from './core/machine-census.js'
export * from './keymap.js'
export * from './keymap-format.js'
export * from './platform.js'
export { normalizeCell, isValidCell } from './cell.js'
export * from './i18n.types.js'
export * from './command-object.js'
export * from './icon-pick.types.js'
export * from './remote-submit.types.js'
export * from './usage.types.js'
export * from './theme.types.js'
export * from './core/canonical-layer.js'
export * from './core/location-marker.js'
export * from './core/host-offerings.js'
export * from './icon-ref.js'
export * from './tile-content-renderer.js'
export * from './confirm.js'
export * from './substrate.types.js'
export * from './pointer-gesture-consumer.js'
export * from './portable-tile.js'
export * from './core/client-identity.js'
export * from './core/assistant-chat-config.js'
export * from './core/local-claude-bridge.js'
export * from './core/llm-keys.js'
export * from './core/sandbox-door.js'
export * from './core/secret-words/index.js'
export * from './core/revision-name.js'
export * from './core/behaviour-call.js'
export * from './question-fence.js'

// The PANEL KIT — the docked tool-window model, moved out of the Angular shell
// (2026-09-01) so a behaviour can build its own chrome. Framework-free by
// construction: a module may only import from core, and the shim cannot load
// Angular at all. `docked-panel.js` is the primitive itself; the rest is the
// model it drives (lanes, groups, settings rows, sessions, breakpoints).
export * from './core/panels/breakpoints.js'
export * from './core/panels/window-session.js'
export * from './core/panels/window-rule.js'
export * from './core/panels/dock-lanes.js'
export * from './core/panels/panel-groups.js'
export * from './core/panels/panel-settings.js'
export * from './core/panels/tool-windows.js'
export * from './core/panels/docked-panel.js'
export * from './retired-exports.js'
