#!/usr/bin/env node
// scripts/write-env-js.cjs
//
// Writes public/env.js for one or more apps. Used by CI to ensure the file
// always exists in production builds (the front-end loads it unconditionally
// from index.html, so a missing file = 404 spam in the console).
//
// If ANTHROPIC_API_KEY is set in the environment, env.js seeds it into
// localStorage on first load. Otherwise it writes a no-op stub.
//
// SECURITY: ANY value written here is shipped to every visitor's browser
// and is trivially extractable. Only set ANTHROPIC_API_KEY in CI if you
// genuinely intend to expose that key publicly. Prefer a backend proxy
// (e.g. an Azure Function reading SWA Application Settings) for real keys.
//
// Usage:
//   node scripts/write-env-js.cjs <app-public-dir> [<app-public-dir> ...]
//
// Example:
//   ANTHROPIC_API_KEY=sk-ant-... node scripts/write-env-js.cjs \
//     hypercomb-web/dist/hypercomb-web/browser \
//     diamond-core-processor/dist/diamond-core-processor/browser

const fs = require('fs')
const path = require('path')

const targets = process.argv.slice(2)
if (targets.length === 0) {
  console.error('[write-env-js] no target directories provided')
  process.exit(1)
}

const apiKey = process.env.ANTHROPIC_API_KEY || ''

const content = apiKey
  ? [
      '// Generated by CI \u2014 do not commit',
      `if (!localStorage.getItem('hc:anthropic-api-key')) {`,
      `  localStorage.setItem('hc:anthropic-api-key', ${JSON.stringify(apiKey)})`,
      `}`,
      '',
    ].join('\n')
  : '// No ANTHROPIC_API_KEY configured for this build\n'

let wrote = 0
for (const target of targets) {
  if (!fs.existsSync(target)) {
    console.warn(`[write-env-js] target directory does not exist, skipping: ${target}`)
    continue
  }
  const dest = path.join(target, 'env.js')
  fs.writeFileSync(dest, content, 'utf8')
  console.log(`[write-env-js] wrote ${dest}${apiKey ? ' (key present)' : ' (stub)'}`)
  wrote++
}

if (wrote === 0) {
  console.error('[write-env-js] no env.js files were written')
  process.exit(1)
}
