// auto-generated by scripts/prepare.ts
// public module keys for diamondcoreprocessor.com/settings
// do not edit manually

export const SettingsModule = 'diamondcoreprocessor.com/settings'
export const ZoomSettings = 'diamondcoreprocessor.com/settings/zoom-settings'
export const ZoomSettingsType = 'diamondcoreprocessor.com/settings/zoom-settings'
export const SettingsKeys = { ZoomSettings, ZoomSettingsType } as const
