//! # `hypercomb-protocol`
//!
//! The Hypercomb protocol: signatures, lineage keys, pools of meaning, canonical
//! layers, and markers.
//!
//! **This crate is pure.** No filesystem, no network, no clock, no globals — it
//! turns bytes into signatures and back. That is what makes it testable against
//! the conformance vectors and compilable to `wasm32`, so the web shell can
//! eventually adopt the same implementation rather than maintaining a parallel
//! one.
//!
//! The contract it implements is specified in
//! `documentation/protocol/conformance.md`, and every rule there is asserted
//! against `hypercomb-client/conformance/vectors.json` — vectors generated by
//! executing the live TypeScript implementation, never transcribed.
//!
//! ## The three things worth knowing
//!
//! 1. **Signatures are typed.** [`BagAddr`] and [`PoolAddr`] are distinct types
//!    that do not convert implicitly, because they are indistinguishable on disk
//!    and confusing them has destroyed data. See [`sig`].
//!
//! 2. **There are two canonicalization rules, not one.** Layers sort their slots
//!    ([`layer`]); bee payloads preserve insertion order ([`payload`]). They live
//!    apart so they cannot be mixed up.
//!
//! 3. **The maximum marker in a bag is the head.** There is no head pointer, and
//!    therefore none to corrupt. See [`marker`].

#![forbid(unsafe_code)]
#![warn(missing_debug_implementations)]

pub mod layer;
pub mod lineage;
pub mod marker;
pub mod payload;
pub mod pool;
pub mod sig;

pub use layer::{Layer, ROOT_NAME};
pub use lineage::{bag_addr, canonicalize_segment, legacy_bag_addr, lineage_key, raw_lineage_key};
pub use marker::{marker_filename, marker_index, Marker, MARKER_WIDTH};
pub use payload::{sign_payload, BeePayloadV1};
pub use pool::{PoolRegistry, BARE_WORD_MEANINGS, SCOPED_MEANINGS};
pub use sig::{sign, sign_str, BagAddr, LayerSig, PoolAddr, Sig};
