//! The conformance suite.
//!
//! Asserts this crate against `hypercomb-client/conformance/vectors.json` —
//! ground truth generated by executing the live TypeScript implementation.
//!
//! These vectors are the crate's definition of done. If the TypeScript protocol
//! logic changes, regenerating the vectors makes this suite fail loudly, which
//! is the entire point: it is the mechanism that prevents two implementations
//! from silently forking their merkle trees.

use std::path::PathBuf;

use hypercomb_protocol::{
    bag_addr, canonicalize_segment, layer::Layer, lineage_key, marker_filename, pool::PoolRegistry,
    raw_lineage_key, sign, sign_str, Marker, Sig,
};
use serde_json::Value;

fn vectors() -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../conformance/vectors.json")
        .canonicalize()
        .expect("conformance/vectors.json must exist — run generate-vectors.ts");
    let text = std::fs::read_to_string(path).expect("vectors readable");
    serde_json::from_str(&text).expect("vectors parse")
}

/// Segments arrive as JSON values; the generator feeds non-strings through
/// `String(raw ?? '')`, so mirror that coercion here.
fn segment_strings(value: &Value) -> Vec<String> {
    value
        .as_array()
        .expect("segments is an array")
        .iter()
        .map(|v| match v {
            Value::String(s) => s.clone(),
            Value::Null => String::new(),
            other => other.to_string(),
        })
        .collect()
}

#[test]
fn signatures_match() {
    let vectors = vectors();
    let cases = vectors["signatures"].as_array().unwrap();
    assert!(!cases.is_empty(), "expected signature vectors");

    for case in cases {
        let input = case["input"].as_str().unwrap();
        let expected = case["signature"].as_str().unwrap();

        assert_eq!(
            sign_str(input).to_hex(),
            expected,
            "signature mismatch for {input:?}"
        );

        // The generator also pins the exact UTF-8 bytes it hashed, so a
        // mismatch distinguishes "wrong encoding" from "wrong hash".
        let expected_bytes = case["inputUtf8Hex"].as_str().unwrap();
        let actual_bytes: String = input.as_bytes().iter().map(|b| format!("{b:02x}")).collect();
        assert_eq!(actual_bytes, expected_bytes, "UTF-8 encoding differs for {input:?}");
    }
}

#[test]
fn the_root_signs_as_the_empty_hash() {
    let vectors = vectors();
    let expected = vectors["signatures"][0]["signature"].as_str().unwrap();
    assert_eq!(Sig::empty().to_hex(), expected);

    let empty: [&str; 0] = [];
    assert_eq!(
        bag_addr(&empty).to_hex(),
        expected,
        "the root bag address IS the empty hash — this collision is load-bearing"
    );
}

#[test]
fn lineage_keys_match() {
    let vectors = vectors();
    let cases = vectors["lineageKeys"].as_array().unwrap();
    assert!(!cases.is_empty(), "expected lineage vectors");

    for case in cases {
        let segments = segment_strings(&case["segments"]);
        let label = format!("{segments:?}");

        assert_eq!(
            lineage_key(&segments),
            case["canonicalKey"].as_str().unwrap(),
            "canonical key mismatch for {label}"
        );
        assert_eq!(
            bag_addr(&segments).to_hex(),
            case["bagAddress"].as_str().unwrap(),
            "bag address mismatch for {label}"
        );
        assert_eq!(
            raw_lineage_key(&segments),
            case["legacyRawKey"].as_str().unwrap(),
            "legacy raw key mismatch for {label}"
        );

        let expected_per_segment: Vec<&str> = case["perSegmentCanonical"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap())
            .collect();
        let actual_per_segment: Vec<String> =
            segments.iter().map(|s| canonicalize_segment(s)).collect();
        assert_eq!(
            actual_per_segment, expected_per_segment,
            "per-segment canonicalization mismatch for {label}"
        );
    }
}

#[test]
fn pool_addresses_and_the_collision_census_match() {
    let vectors = vectors();
    let cases = vectors["poolAddresses"].as_array().unwrap();
    assert!(!cases.is_empty(), "expected pool vectors");

    let mut registry = PoolRegistry::new();
    let mut collisions = 0;

    for case in cases {
        let meaning = case["meaning"].as_str().unwrap();

        assert_eq!(
            registry.address(meaning).to_hex(),
            case["address"].as_str().unwrap(),
            "pool address mismatch for {meaning}"
        );

        let expected_collision = case["collidesWithSameNamedTile"].as_bool().unwrap();
        let actual_collision = hypercomb_protocol::pool::collides_with_lineage(meaning);
        assert_eq!(
            actual_collision, expected_collision,
            "collision verdict differs for {meaning}"
        );

        if expected_collision {
            collisions += 1;
            // A colliding meaning IS a lineage bag address for a same-named
            // root tile. That hazard is the reason the registry exists.
            assert_eq!(registry.address(meaning).sig(), bag_addr(&[meaning]).sig());
        } else {
            assert!(meaning.contains(':'), "{meaning} avoids collision only by carrying a colon");
        }
    }

    assert!(
        collisions > 0,
        "the census should record real collisions — a zero here means the check is broken, not that the tree is safe"
    );
}

#[test]
fn canonical_layers_match() {
    let vectors = vectors();
    let cases = vectors["layers"].as_array().unwrap();
    assert!(!cases.is_empty(), "expected layer vectors");

    for case in cases {
        let note = case["note"].as_str().unwrap();
        let input = case["input"].as_object().unwrap();

        let mut layer = Layer::empty(input["name"].as_str().unwrap_or_default());
        for (key, value) in input {
            if key != "name" {
                layer.set(key.clone(), value.clone());
            }
        }

        assert_eq!(
            layer.canonical_json(),
            case["canonicalJson"].as_str().unwrap(),
            "canonical JSON mismatch: {note}"
        );
        assert_eq!(
            layer.sig().to_hex(),
            case["signature"].as_str().unwrap(),
            "layer signature mismatch: {note}"
        );
    }
}

#[test]
fn markers_match() {
    let vectors = vectors();
    let markers = &vectors["markers"];

    // Filenames.
    let expected_names: Vec<&str> = markers["markerFilenames"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap())
        .collect();
    for (index, expected) in [0u32, 1, 2, 42, 99999999].iter().zip(expected_names) {
        assert_eq!(marker_filename(*index), expected);
    }

    // Pointer record.
    let pointer = &markers["pointerRecord"];
    let layer = Layer::from_json(pointer["layerJson"].as_str().unwrap().as_bytes()).unwrap();
    assert_eq!(layer.sig().to_hex(), pointer["layerSig"].as_str().unwrap());

    let parsed = Marker::parse(pointer["markerBytes"].as_str().unwrap().as_bytes());
    assert!(!parsed.is_legacy(), "a {{\"layer\":<sig>}} record is a pointer");
    assert_eq!(parsed.layer().to_hex(), pointer["layerSig"].as_str().unwrap());

    // Legacy inline record: the bytes ARE the layer.
    let legacy = &markers["legacyInlineRecord"];
    let legacy_bytes = legacy["markerBytes"].as_str().unwrap().as_bytes();
    let parsed = Marker::parse(legacy_bytes);
    assert!(parsed.is_legacy(), "layer JSON with no `layer` field is legacy");
    assert_eq!(
        parsed.layer().to_hex(),
        legacy["derivedLayerSig"].as_str().unwrap(),
        "a legacy marker's layer sig is the hash of its own bytes"
    );
    assert_eq!(sign(legacy_bytes).to_hex(), legacy["derivedLayerSig"].as_str().unwrap());
}

#[test]
fn bee_payloads_use_insertion_order() {
    let vectors = vectors();
    let case = &vectors["beePayload"];

    let canonical = case["canonicalJson"].as_str().unwrap();
    assert_eq!(
        sign(canonical.as_bytes()).to_hex(),
        case["signature"].as_str().unwrap()
    );

    // The distinguishing property: re-serializing the parsed payload must
    // reproduce the ORIGINAL key order, not a sorted one.
    let payload: hypercomb_protocol::BeePayloadV1 = serde_json::from_str(canonical).unwrap();
    assert_eq!(payload.canonical_json(), canonical);
    assert_eq!(payload.sig().to_hex(), case["signature"].as_str().unwrap());
}
