// assistant/providers/builtin-providers.ts
//
// THE ROSTER THAT SHIPS. Importing this file registers every vendor adapter
// that comes in the box; `llm-dispatch.ts` imports it, so any caller of the
// seam gets the full roster whether or not anything else has loaded yet.
//
// It is a hand-written barrel rather than the generated per-folder `index.ts`
// because that file is regenerated by `npm run prepare` and would lose the
// side-effect ordering guarantee (and any comment explaining it). Adding a
// vendor is one import line here plus its descriptor file — nothing else in
// the codebase learns the name.

import './anthropic.provider.js'
import './openai.provider.js'
import './google.provider.js'
import './xai.provider.js'
import './deepseek.provider.js'
import './mistral.provider.js'
import './local.provider.js'

// Not a vendor either: the heartbeat that asks the machine's own model server
// whether it is actually running. Imported AFTER the descriptors so the first
// sweep sees the whole roster — and here rather than inside local.provider so
// the descriptor file stays a descriptor.
import { startLocalLivenessWatch } from './local-liveness.js'

// Not a vendor: the sweep that adds every DISCOVERED provider (specs in the
// `llm:providers` pool) to the same roster, the moment the store is ready.
import './provider-discovery.js'

startLocalLivenessWatch()

export {}
