// auto-generated by scripts/prepare.ts
// public module keys for diamondcoreprocessor.com/pixi
// do not edit manually

export const PixiModule = 'diamondcoreprocessor.com/pixi'
export const HexLabelAtlas = 'diamondcoreprocessor.com/pixi/hex-label.atlas'
export const HexSdfTextureShader = 'diamondcoreprocessor.com/pixi/hex-sdf.shader'
export const LabelUV = 'diamondcoreprocessor.com/pixi/hex-label.atlas'
export const PixiKeys = { HexLabelAtlas, HexSdfTextureShader, LabelUV } as const
