// games/arkanoid/themes/register-themes.ts
//
// Every BUILT-IN scene theme, in picker order. The themes only export;
// arkanoid.drone.ts registers this list (registration is the bee's act —
// atomic-modules-plan.md). Hand-written and tracked on purpose —
// themes/index.ts is auto-generated by the prepare script and gitignored, so
// it cannot be a load-bearing import target. New built-in themes go here.

import type { ArkanoidTheme } from '../theme.js'
import { hauntedKeep } from './haunted-keep.js'
import { neonGrid } from './neon-grid.js'
import { spaceMadness } from './space-madness.js'

export const BUILT_IN_THEMES: readonly ArkanoidTheme[] = [hauntedKeep, neonGrid, spaceMadness]
