export declare const relPosix: (from: string, to: string) => string;
export declare const walkFiles: (dir: string) => string[];
export declare const ensureDir: (dir: string) => void;
export declare const rmDir: (dir: string) => void;
export declare const isDrone: (file: string) => boolean;
export declare const stripExt: (p: string) => string;
export declare const fileBase: (p: string) => string;
export declare const textToBytes: (text: string) => Uint8Array;
export declare const toArrayBuffer: (bytes: Uint8Array) => ArrayBuffer;
export declare const isSig: (v: string) => boolean;
export declare const writeSigFile: (dir: string, sig: string, bytes: Uint8Array) => void;
export declare const readText: (path: string) => string;
export declare const isUnderDir: (file: string, dirAbs: string) => boolean;
export declare const readEssentialsTokenFromFirstLine: (text: string) => string | null;
export declare const normalizeEssentialsSpecifier: (token: string | null, base: string) => string;
export declare const toNamespace: (specifier: string) => string;
export declare const stripLeadingEssentialsHeaderLine: (text: string) => string;
//# sourceMappingURL=_shared.d.ts.map