#!/usr/bin/env node
// Regenerate src/presentation/fonts/package-fonts.ts from the shells'
// canonical faces (hypercomb-shim/public/fonts, written by
// scripts/fetch-fonts.cjs and byte-identical across the shells).
//
// The package carries the faces it renders that the minimal host does not
// ship: the icon face and the italic reading serif. The host ships Inter and
// upright Source Serif 4 (hypercomb-shim/host/check-pure.mjs).
//
//   node scripts/package-fonts.mjs          rewrite the data file
//   node scripts/package-fonts.mjs --check  exit 1 if it is stale
import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
export const FONTS_DIR = resolve(here, '..', '..', 'hypercomb-shim', 'public', 'fonts')
const OUT = resolve(here, '..', 'src', 'presentation', 'fonts', 'package-fonts.ts')

const carried = face => face.family === 'Material Symbols Outlined'
  || (face.family === 'Source Serif 4' && face.style === 'italic')

export const readPackageFonts = () => {
  const css = readFileSync(resolve(FONTS_DIR, 'fonts.css'), 'utf8')
  const faces = []
  for (const block of css.split('@font-face').slice(1)) {
    const field = name => (new RegExp(`${name}:\\s*([^;]+);`).exec(block)?.[1] ?? '').trim()
    const file = /url\(\.\/([^?)]+)/.exec(block)?.[1]
    const face = {
      family: field('font-family').replace(/^'|'$/g, ''),
      style: field('font-style') || 'normal',
      weight: field('font-weight') || '400',
      display: field('font-display') || 'swap',
      unicodeRange: field('unicode-range'),
      file,
    }
    if (!file || !carried(face)) continue
    faces.push(face)
  }
  return faces
}

/** The signature of a face's bytes, as the build names it in the root layer. */
export const fontSignature = file =>
  createHash('sha256').update(readFileSync(resolve(FONTS_DIR, file))).digest('hex')

const render = faces => `// presentation/fonts/package-fonts.ts — GENERATED by scripts/package-fonts.mjs.
// Do not edit: rerun the script after scripts/fetch-fonts.cjs changes a face.
//
// The faces this package renders that the minimal host does not ship. The
// build signs each file and names it, with these descriptors, in the root
// layer's \`resources\` (scripts/build-module.ts); fonts.boot.drone.ts reads
// them from there and declares a face only where the page has none for its
// family and style. No signature lives in source.

export type PackageFont = {
  family: string
  style: string
  weight: string
  display: string
  unicodeRange: string
  file: string
}

export const PACKAGE_FONTS: readonly PackageFont[] = ${JSON.stringify(faces, null, 2).replace(/"([a-zA-Z]+)":/g, '$1:').replace(/"/g, "'")}
`

if (import.meta.url === `file://${process.argv[1]}`) {
  const text = render(readPackageFonts())
  if (process.argv.includes('--check')) {
    let current = ''
    try { current = readFileSync(OUT, 'utf8') } catch {}
    if (current !== text) { console.error('[package-fonts] stale: run node scripts/package-fonts.mjs'); process.exit(1) }
    console.log('[package-fonts] up to date')
  } else {
    writeFileSync(OUT, text)
    console.log(`[package-fonts] wrote ${OUT}`)
  }
}
