// hypercomb-essentials/scripts/prepare.ts
// generates ambient externals per domain by parsing real exports
// - domains = first-level folders under src (except "types")
// - namespaces = @<domain>/<up to 2 subfolders>
// - folders only (never files) define module names
// - explicit symbol exports only
// - no runtime output
// - deterministic

import { existsSync, readdirSync, statSync, readFileSync, writeFileSync, mkdirSync } from 'fs'
import { join, resolve, dirname, extname } from 'path'
import ts from 'typescript'
import { fileURLToPath } from 'url'

// -------------------------------------------------
// anchors
// -------------------------------------------------

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

// -------------------------------------------------
// config
// -------------------------------------------------

const SRC_ROOT = resolve(__dirname, '../src')
const TYPES_ROOT = resolve(SRC_ROOT, 'types')

// -------------------------------------------------
// helpers
// -------------------------------------------------

const isSource = (f: string): boolean =>
  (f.endsWith('.ts') || f.endsWith('.js')) &&
  !f.endsWith('.d.ts') &&
  !f.endsWith('.drone.ts') &&
  !f.endsWith('.drone.js')

const walk = (dir: string): string[] => {
  if (!existsSync(dir)) return []
  const out: string[] = []

  for (const name of readdirSync(dir)) {
    const full = join(dir, name)
    const st = statSync(full)

    if (st.isDirectory()) out.push(...walk(full))
    else out.push(full)
  }

  return out
}

// -------------------------------------------------
// export parsing
// -------------------------------------------------

type ExportInfo = {
  value: string[]
  type: string[]
}

const parseExports = (file: string): ExportInfo => {
  const source = ts.createSourceFile(
    file,
    readFileSync(file, 'utf8'),
    ts.ScriptTarget.Latest,
    true
  )

  const out: ExportInfo = { value: [], type: [] }

  source.forEachChild(node => {
    if (
      ts.canHaveModifiers(node) &&
      node.modifiers?.some(m => m.kind === ts.SyntaxKind.ExportKeyword)
    ) {
      if (
        ts.isClassDeclaration(node) ||
        ts.isFunctionDeclaration(node) ||
        ts.isEnumDeclaration(node)
      ) {
        if (node.name) out.value.push(node.name.text)
      }

      if (ts.isVariableStatement(node)) {
        node.declarationList.declarations.forEach(d => {
          if (ts.isIdentifier(d.name)) out.value.push(d.name.text)
        })
      }

      if (ts.isInterfaceDeclaration(node) || ts.isTypeAliasDeclaration(node)) {
        out.type.push(node.name.text)
      }
    }

    if (
      ts.isExportDeclaration(node) &&
      node.exportClause &&
      ts.isNamedExports(node.exportClause)
    ) {
      node.exportClause.elements.forEach(e => {
        const name = (e.name || e.propertyName)?.text
        if (name) out.value.push(name)
      })
    }
  })

  return out
}

// -------------------------------------------------
// namespace helpers
// -------------------------------------------------

const getNamespace = (domain: string, file: string): string | null => {
  const rel = file
    .replace(join(SRC_ROOT, domain), '')
    .replace(/^[\\/]/, '')

  const parts = rel.split(/[\\/]/)

  parts.pop()

  if (parts.length === 0) {
    return `@${domain}`
  }

  return `@${[domain, ...parts.slice(0, 2)].join('/')}`
}

const getModulePath = (domain: string, file: string): string =>
  '../' +
  join(domain, file.replace(join(SRC_ROOT, domain), ''))
    .replace(/^[\\/]/, '')
    .replace(extname(file), '')
    .replace(/\\/g, '/')

// -------------------------------------------------
// main
// -------------------------------------------------

mkdirSync(TYPES_ROOT, { recursive: true })

const domains = readdirSync(SRC_ROOT).filter(name => {
  if (name === 'types') return false
  const full = join(SRC_ROOT, name)
  return statSync(full).isDirectory()
})

for (const domain of domains) {
  const domainRoot = join(SRC_ROOT, domain)

  const namespaces = new Map<string, Map<string, ExportInfo>>()

  for (const file of walk(domainRoot)) {
    if (!isSource(file)) continue

    const exports = parseExports(file)
    if (!exports.value.length && !exports.type.length) continue

    const ns = getNamespace(domain, file)
    if (!ns) continue

    const mod = getModulePath(domain, file)
    const bucket = namespaces.get(ns) ?? new Map()
    bucket.set(mod, exports)
    namespaces.set(ns, bucket)
  }

  if (!namespaces.size) continue

  const outFile = join(TYPES_ROOT, `${domain}.externals.d.ts`)

  let out = `// auto-generated by scripts/prepare.ts
// ambient externals for ${domain}
// do not edit manually

`

  for (const [ns, modules] of namespaces) {
    out += `declare module '${ns}' {\n`

    for (const [mod, exp] of modules) {
      if (exp.value.length) {
        out += `  export { ${exp.value.join(', ')} } from '${mod}'\n`
      }
      if (exp.type.length) {
        out += `  export type { ${exp.type.join(', ')} } from '${mod}'\n`
      }
    }

    out += `}\n\n`
  }

  writeFileSync(outFile, out, 'utf8')
  console.log(`[prepare] wrote ${outFile}`)
}
