const path = require('node:path')

const TEXT_EXTENSIONS = new Set([
  '.c', '.cc', '.cjs', '.cpp', '.css', '.csv', '.go', '.graphql', '.h', '.html',
  '.java', '.js', '.json', '.jsonc', '.jsx', '.kt', '.less', '.md', '.mjs',
  '.php', '.ps1', '.py', '.rb', '.rs', '.scss', '.sh', '.sql', '.svg', '.toml',
  '.ts', '.tsx', '.txt', '.vue', '.xml', '.yaml', '.yml',
])

const LANGUAGE_BY_EXTENSION = {
  '.c': 'c', '.cc': 'cpp', '.cjs': 'javascript', '.cpp': 'cpp', '.css': 'css',
  '.go': 'go', '.graphql': 'graphql', '.h': 'c-header', '.html': 'html',
  '.java': 'java', '.js': 'javascript', '.json': 'json', '.jsonc': 'jsonc',
  '.jsx': 'javascript-react', '.kt': 'kotlin', '.less': 'less', '.md': 'markdown',
  '.mjs': 'javascript', '.php': 'php', '.ps1': 'powershell', '.py': 'python',
  '.rb': 'ruby', '.rs': 'rust', '.scss': 'scss', '.sh': 'shell', '.sql': 'sql',
  '.svg': 'svg', '.toml': 'toml', '.ts': 'typescript', '.tsx': 'typescript-react',
  '.txt': 'text', '.vue': 'vue', '.xml': 'xml', '.yaml': 'yaml', '.yml': 'yaml',
}

function textOf(file) {
  return file.text == null ? null : file.text
}

const definitions = [
  {
    id: 'repo/file-role', version: 1, usesPath: true,
    run(file) {
      const p = file.path.toLowerCase().replaceAll('\\', '/')
      const base = path.posix.basename(p)
      let role = 'source'
      if (/(^|\/)(dist|build|coverage|target|out)(\/|$)/.test(p)) role = 'build-output'
      else if (/(^|\/)(vendor|third_party)(\/|$)/.test(p)) role = 'vendored'
      else if (/\.(spec|test)\.[^.]+$/.test(base) || /(^|\/)tests?(\/|$)/.test(p)) role = 'test'
      else if (/(^|\/)(fixtures?|test-data|snapshots?)(\/|$)/.test(p) || /\.snap$/.test(base)) role = 'fixture'
      else if (/\.(md|mdx|rst)$/.test(base) || /(^|\/)documentation(\/|$)/.test(p)) role = 'documentation'
      else if (/^(package(-lock)?\.json|tsconfig.*\.json|angular\.json|vite\.config\.|webpack\.config\.|eslint\.config\.|\.gitignore)/.test(base) || /\.(ya?ml|toml)$/.test(base)) role = 'configuration'
      return { matched: true, value: { role } }
    },
  },
  {
    id: 'repo/language-format', version: 1, usesPath: true,
    run(file) {
      const ext = path.extname(file.path).toLowerCase()
      const language = LANGUAGE_BY_EXTENSION[ext]
      return { matched: true, value: language ? { language, text: true } : { language: 'binary-or-unknown', text: false } }
    },
  },
  {
    id: 'repo/generated-file', version: 1, usesPath: true,
    run(file) {
      const text = textOf(file)
      const p = file.path.toLowerCase().replaceAll('\\', '/')
      const reasons = []
      if (/(^|\/)(dist|build|coverage|generated|target|out)(\/|$)/.test(p)) reasons.push('generated-directory')
      if (/\.(min\.js|map|lock)$/.test(p) || /(^|\/)package-lock\.json$/.test(p)) reasons.push('generated-extension')
      if (text && /(@generated|auto-generated|autogenerated|do not edit|generated file)/i.test(text.slice(0, 2048))) reasons.push('generated-banner')
      return { matched: reasons.length > 0, value: { generated: reasons.length > 0, reasons } }
    },
  },
  {
    id: 'repo/symbol-inventory', version: 1,
    run(file) {
      const text = textOf(file)
      if (text == null) return { status: 'unsupported', value: { reason: 'not-text' } }
      const symbols = new Set()
      const patterns = [
        /\bexport\s+(?:default\s+)?(?:abstract\s+)?(?:async\s+)?(?:class|function|const|let|var|interface|type|enum)\s+([A-Za-z_$][\w$]*)/g,
        /\b(?:class|def|fn|func)\s+([A-Za-z_$][\w$]*)/g,
        /\bmodule\.exports\.([A-Za-z_$][\w$]*)\s*=/g,
      ]
      for (const pattern of patterns) for (const match of text.matchAll(pattern)) symbols.add(match[1])
      return { matched: symbols.size > 0, value: { symbols: [...symbols].sort().slice(0, 500), truncated: symbols.size > 500 } }
    },
  },
  {
    id: 'repo/dependency-edges', version: 1,
    run(file) {
      const text = textOf(file)
      if (text == null) return { status: 'unsupported', value: { reason: 'not-text' } }
      const dependencies = new Set()
      const patterns = [
        /\b(?:import|export)\s+(?:[^'";]*?\s+from\s+)?['"]([^'"]+)['"]/g,
        /\brequire\(\s*['"]([^'"]+)['"]\s*\)/g,
        /\bimport\(\s*['"]([^'"]+)['"]\s*\)/g,
      ]
      for (const pattern of patterns) for (const match of text.matchAll(pattern)) dependencies.add(match[1])
      return { matched: dependencies.size > 0, value: { dependencies: [...dependencies].sort().slice(0, 500), truncated: dependencies.size > 500 } }
    },
  },
  {
    id: 'repo/test-signals', version: 1, usesPath: true,
    run(file) {
      const text = textOf(file)
      if (text == null) return { status: 'unsupported', value: { reason: 'not-text' } }
      const p = file.path.toLowerCase().replaceAll('\\', '/')
      const frameworks = []
      if (/\b(describe|it|test)\s*\(/.test(text)) frameworks.push('js-test-api')
      if (/\bfrom\s+['"]node:test['"]|require\(['"]node:test['"]\)/.test(text)) frameworks.push('node-test')
      if (/\b(pytest|unittest)\b/.test(text)) frameworks.push('python-test')
      if (/#\[test\]/.test(text)) frameworks.push('rust-test')
      const isTest = /\.(spec|test)\.[^.]+$/.test(p) || /(^|\/)tests?(\/|$)/.test(p) || frameworks.length > 0
      return { matched: isTest, value: { isTest, frameworks: [...new Set(frameworks)] } }
    },
  },
  {
    id: 'repo/entrypoint-signals', version: 1, usesPath: true,
    run(file) {
      const text = textOf(file)
      const p = file.path.toLowerCase().replaceAll('\\', '/')
      const signals = []
      if (/(^|\/)(main|index|bootstrap|server|cli)\.[^.]+$/.test(p)) signals.push('conventional-name')
      if (/(^|\/)package\.json$/.test(p)) signals.push('package-manifest')
      if (text && /\b(?:bootstrapApplication|createRoot|new\s+Worker|require\.main\s*===\s*module|if\s+__name__\s*==\s*['"]__main__['"])/.test(text)) signals.push('bootstrap-code')
      return { matched: signals.length > 0, value: { entrypoint: signals.length > 0, signals } }
    },
  },
]

function mayReadAsText(relativePath, bytes) {
  const ext = path.extname(relativePath).toLowerCase()
  if (TEXT_EXTENSIONS.has(ext)) return true
  const sample = bytes.subarray(0, Math.min(bytes.length, 1024))
  return !sample.includes(0)
}

module.exports = { definitions, mayReadAsText }
