// auto-generated by scripts/prepare.ts
// public module keys for diamondcoreprocessor.com/core
// do not edit manually

export const CoreModule = 'diamondcoreprocessor.com/core'
export const Settings = 'diamondcoreprocessor.com/core/settings'
export const CoreKeys = { Settings } as const
