// diamondcoreprocessor.com/games/arkanoid/themes/register-themes.ts
//
// Side-effect module: importing it loads + registers every BUILT-IN scene
// theme (each theme file self-registers at module scope). Hand-written and
// tracked on purpose — themes/index.ts is auto-generated by the prepare
// script and gitignored, so it cannot be a load-bearing import target.
// New built-in themes must be added here.

import './haunted-keep.js'
import './neon-grid.js'
import './space-madness.js'
