// auto-generated
// sleeping lane — self-registering modules that load on demand: a queen on
// her word, a view when entered, a bee on its effect (scripts/passive-queen.ts).
// The dev shell hands this table to the preloader (useSleepers).
// do not edit manually

export type Sleeper = {
  readonly load: () => Promise<unknown>
  readonly command?: string
  readonly description?: string
  readonly renders?: readonly string[]
  readonly wakesOn?: readonly string[]
}

export const sleepers: readonly Sleeper[] = [
  { command: "chat", description: "Open the chat — one conversation per chat, history kept", load: () => import('./assistant/conversation.queen') },
  { wakesOn: ["expand:layer"], load: () => import('./assistant/expand.drone') },
  { command: "file", description: "File a note on the tile it belongs to on this page", load: () => import('./assistant/file.queen') },
  { command: "misses", description: "Show what the hive was asked for but could not do", load: () => import('./assistant/misses.queen') },
  { command: "module", description: "See, drop, try in public, or promote what runs here", load: () => import('./assistant/module.queen') },
  { wakesOn: ["parts:distribute-visual"], load: () => import('./assistant/visual-distribution.drone') },
  { command: "adopt", description: "Take a peer's tile into your hive — the one tile, or with `branch`, everything under it", load: () => import('./commands/adopt.queen') },
  { command: "arrange", description: "Toggle icon arrangement mode on the tile overlay", load: () => import('./commands/arrange.queen') },
  { command: "ask", description: "Open the chat and ask", load: () => import('./commands/ask.queen') },
  { command: "behavior", description: "Bind a behaviour to the tile it belongs to — it shows there and nowhere else", load: () => import('./commands/behavior.queen') },
  { command: "brood", description: "Automatons this hive is holding but will not run — read them, accept one by hand, or set what gets held", load: () => import('./commands/brood.queen') },
  { command: "builds", description: "Build revisions for this subtree — record the state after a build pass, list them, restore one", load: () => import('./commands/builds.queen') },
  { command: "collections", description: "Open the collections entrance", load: () => import('./commands/collections-view.queen') },
  { command: "context", description: "Manage the branches this tile’s AI requests read", load: () => import('./commands/context.queen') },
  { command: "create", description: "Make a tile here — the only way to create one in beehaviour mode", load: () => import('./commands/create.queen') },
  { command: "debug", description: "Toggle the Pixi display-tree inspector", load: () => import('./commands/debug.queen') },
  { command: "deposit", description: "Deposit a signed pheromone — an authored interest-signal on a tile\\", load: () => import('./commands/deposit.queen') },
  { command: "enroll", description: "Relate this tile to a website — the one way artifacts belong together", load: () => import('./commands/enroll.queen') },
  { command: "forget", description: "Show or drop the phrasings the command line learned from you", load: () => import('./commands/forget.queen') },
  { command: "genome", description: "Measure the active hive genome: current markers plus every reachable byte", load: () => import('./commands/genome.queen') },
  { command: "grant", description: "Set how far a machine may go in this hive", load: () => import('./commands/grant.queen') },
  { command: "history", description: "Toggle the history panel", load: () => import('./commands/history.queen') },
  { command: "hive", description: "Give a lineage path or signature a named handle that other slash commands autocomplete against.", load: () => import('./commands/hive.queen') },
  { command: "i18n-override", description: "Override any UI translation (savvy users)", load: () => import('./commands/i18n-override.queen') },
  { command: "interest", description: "Say which pheromones you watch for or never want, and see what\\", load: () => import('./commands/interest.queen') },
  { command: "into", description: "Move the selected tiles inside another tile — they leave this page", load: () => import('./commands/into.queen') },
  { command: "lanes", description: "Toggle three centered lanes for this viewport", load: () => import('./commands/lanes.queen') },
  { command: "language", description: "Switch the UI language; publish, sync or report the community\\", load: () => import('./commands/language.queen') },
  { command: "reference", description: "Drop a reference tile here — a live pointer to another location", load: () => import('./commands/reference.queen') },
  { command: "requires", description: "Manage the pheromones a reference demands of what it shows", load: () => import('./commands/requires.queen') },
  { command: "restore", description: "Go back to a named snapshot — its tiles and behaviours become the live hive again", load: () => import('./commands/restore.queen') },
  { command: "rewind", description: "Open the visual rewind window", load: () => import('./commands/rewind.queen') },
  { command: "slice", description: "Choose a handful of tiles as one merkle slice — an agent-or-participant-chosen set that projects as one", load: () => import('./commands/slice.queen') },
  { command: "spotlight", description: "Light a tile up until it is found", load: () => import('./commands/spotlight.queen') },
  { command: "tags", description: "Open the tag view", load: () => import('./commands/tags-view.queen') },
  { command: "theme", description: "Switch the UI theme (light, dark, system, or a registered theme)", load: () => import('./commands/theme.queen') },
  { command: "title", description: "Set a tile's display name without moving it", load: () => import('./commands/title.queen') },
  { command: "upgrade", description: "Open Packages — what loads, and what has an update. `upgrade allow` lets your followed publisher\\", load: () => import('./commands/upgrade.queen') },
  { command: "verify-history", description: "Walk the current location's history forward and backward; verify undo and redo render the same tile count at every position", load: () => import('./commands/verify-history.queen') },
  { command: "view-current", description: "Show the current branch as a fully-expanded object", load: () => import('./commands/view-current.queen') },
  { command: "views", description: "Show the views this layer can be drawn as", load: () => import('./commands/views.queen') },
  { wakesOn: ["hidden:refresh","hidden:reveal","hidden:delete"], load: () => import('./concealment/concealment.drone') },
  { command: "contact", description: "Enable contact cards for this location\\", load: () => import('./contact/contact.queen') },
  { renders: ["document"], load: () => import('./document/document-view.drone') },
  { wakesOn: ["files:teaser:request","files:teaser:request-pin","files:teaser:request-hide"], load: () => import('./files/files-teaser.drone') },
  { command: "files", description: "Browse files attached to the selected tiles, or every tile in view", load: () => import('./files/files.queen') },
  { command: "format", description: "Copy visual formatting from the active tile", load: () => import('./format/format.queen') },
  { command: "consolidate-history", description: "Relocate leftover legacy history bags to the root and remove the drained folder", load: () => import('./history/consolidate-history.queen') },
  { wakesOn: ["history:promoted"], load: () => import('./history/rewound-commit.drone') },
  { command: "meeting", description: "Start or join a video meeting on the selected tile", load: () => import('./meeting/meeting.queen') },
  { command: "layout", description: "Save, apply, list, or remove layout templates", load: () => import('./move/layout.queen') },
  { command: "fit", description: "Zoom to fit all visible content", load: () => import('./navigation/zoom/fit.queen') },
  { command: "screensaver", description: "Idle screensaver: toggle on/off, pick the look (hexagon, circle, thought…) and the motion (bounce, shooting-stars…)", load: () => import('./presentation/screensaver/screensaver.queen') },
  { command: "hide", description: "Take tiles out of view here, keeping everything they hold", load: () => import('./presentation/tiles/hide.queen') },
  { renders: ["living-brief"], load: () => import('./presentation/tiles/living-brief-view.drone') },
  { renders: ["slides","lightbox","scroller"], load: () => import('./presentation/tiles/slides-view.drone') },
  { renders: ["square-tile-view"], load: () => import('./presentation/tiles/square-tile-view.drone') },
  { renders: ["evidence-atlas","knowledge-studio"], load: () => import('./presentation/tiles/view-library.drone') },
  { command: "record", description: "Start AI-powered meeting recording with live hierarchy compilation", load: () => import('./recording/recording.queen') },
  { command: "feed", description: "On a group, switch a page it feeds on or off", load: () => import('./references/gather/feed.queen') },
  { command: "from", description: "Gather this page from a group — what you make here is made in the group", load: () => import('./references/gather/from.queen') },
  { command: "references", description: "Open Portals and References together to see and manage this page\\", load: () => import('./references/gather/references.queen') },
  { command: "select", description: "Pick tiles by tapping them, then act on the set", load: () => import('./selection/select.queen') },
  { command: "frame", description: "Read this branch through a fixed pattern", load: () => import('./sequence/frame.queen') },
  { command: "pattern", description: "Draw a tile shape a frame can be read through", load: () => import('./sequence/pattern.queen') },
  { command: "sequence", description: "Open Tile arrangements or edit a named drop-target sequence", load: () => import('./sequence/sequence.queen') },
  { command: "arrival", description: "Name what a published branch\\", load: () => import('./sharing/arrival.queen') },
  { command: "features", description: "Which features exist only for participants — readers of your published sites never load them", load: () => import('./sharing/features.queen') },
  { command: "folder-sync", description: "Back up the complete local hive to a private folder, USB disk, NAS, or cloud-synced directory", load: () => import('./sharing/folder-sync.queen') },
  { wakesOn: ["swarm:leader-moved"], load: () => import('./sharing/follow.drone') },
  { command: "hosts", description: "Open your host directory — add or remove a host, inspect its packages, and add one to your hive. Publish uses this directory for branch destinations.", load: () => import('./sharing/hosts.queen') },
  { command: "invite", description: "Invite people to your current meeting place. With a tile selected, stamps it as a swarm junction; always copies a shareable link.", load: () => import('./sharing/invite.queen') },
  { command: "publish", description: "Show what your published hive is serving right now, next to what has changed here since — one row per branch, with publish, re-check and unpublish per row. `publish here` publishes the layer you stand on to its hosts.", load: () => import('./sharing/publish.queen') },
  { command: "repush", description: "Re-push shared content to your host and report holes", load: () => import('./sharing/repush.queen') },
  { wakesOn: ["swarm:subscribe-request-received","swarm:consent-accept","swarm:consent-decline"], load: () => import('./sharing/subscribe-consent.drone') },
  { command: "trust", description: "Say whose code may run your hive — trust a domain, withdraw it, or list them.", load: () => import('./sharing/trust.queen') },
  { command: "heal", description: "Restore participant pictures a default overwrote", load: () => import('./substrate/heal.queen') },
  { command: "reroll", description: "Reroll substrate background images on tiles", load: () => import('./substrate/reroll.queen') },
  { command: "substrate", description: "Manage substrate background image sources", load: () => import('./substrate/substrate.queen') },
  { command: "tutorial", description: "Open the tutorials window — every course and lesson, or fly one by name", load: () => import('./tutorial/tutorial.queen') },
]
