const path = 'assets\\temp-media'

export const SvgContents = [
    { name: 'AI Search Icon', svgPath: `${path}\\ai-search-icon.svg` },
    { name: 'Asset 1', svgPath: `${path}\\Asset 1.svg` },
    { name: 'Asset 13', svgPath: `${path}\\Asset 13.svg` },
    { name: 'Asset 2', svgPath: `${path}\\Asset 2.svg` },
    { name: 'Asset 3', svgPath: `${path}\\Asset 3.svg` },
    { name: 'Asset 3d', svgPath: `${path}\\Asset 3d.svg` },
    { name: 'Asset 4', svgPath: `${path}\\Asset 4.svg` },
    { name: 'Asset 5', svgPath: `${path}\\Asset 5.svg` },
    { name: 'Asset 6', svgPath: `${path}\\Asset 6.svg` },
    { name: 'Asset 7', svgPath: `${path}\\Asset 7.svg` },
    { name: 'Asset s1', svgPath: `${path}\\Asset s1.svg` },
    { name: 'Asset s2', svgPath: `${path}\\Asset s2.svg` },
    { name: 'Branch Background', svgPath: `${path}\\branch-background.svg` },
    { name: 'Branch Blood Shed', svgPath: `${path}\\branch-blood-shed.svg` },
    { name: 'Branch Completed', svgPath: `${path}\\branch-completed.svg` },
    { name: 'Branch Completed 2024_07_03_23_40_56.0', svgPath: `${path}\\branch-completed.svg.2024_07_03_23_40_56.0.svg` },
    { name: 'Branch Hive Icon', svgPath: `${path}\\branch-hive-icon.svg` },
    { name: 'Branch Overlay', svgPath: `${path}\\branch-overlay.svg` },
    { name: 'Clipboard Icon', svgPath: `${path}\\clipboard-icon.svg` },
    { name: 'Common Borders', svgPath: `${path}\\common-borders.svg` },
    { name: 'Copy Cursor', svgPath: `${path}\\copy-cursor.svg` },
    { name: 'Cut Cursor', svgPath: `${path}\\cut-cursor.svg` },
    { name: 'Drag Target', svgPath: `${path}\\drag-target.svg` },
    { name: 'Drawing 1', svgPath: `${path}\\drawing-1.svg` },
    { name: 'Drawing', svgPath: `${path}\\drawing.svg` },
    { name: 'Dynamic Button', svgPath: `${path}\\dynamic-button.svg` },
    { name: 'Edit Cursor', svgPath: `${path}\\edit-cursor.svg` },
    { name: 'Eye Dropper', svgPath: `${path}\\eye-dropper.svg` },
    { name: 'Footer Controls', svgPath: `${path}\\footer-controls.svg` },
    { name: 'Go to Town', svgPath: `${path}\\go-to-town.svg` },
    { name: 'Hand Cursor', svgPath: `${path}\\hand-cursor.svg` },
    { name: 'Header Icons', svgPath: `${path}\\header-icons.svg` },
    { name: 'Help Shortcuts', svgPath: `${path}\\help-shortcuts.svg` },
    { name: 'Hexagon Border Cutout', svgPath: `${path}\\hexagon-border-cutout.svg` },
    { name: 'Hexagon Delete Icon', svgPath: `${path}\\hexagon-delete-icon.svg` },
    { name: 'Hexagon Selection', svgPath: `${path}\\hexagon-selection.svg` },
    { name: 'Home Menu', svgPath: `${path}\\home-menu.svg` },
    { name: 'Hypercomb Designer', svgPath: `${path}\\hypercomb-designer.svg` },
    { name: 'Image Placement', svgPath: `${path}\\image-placement.svg` },
    { name: 'Jaggedy', svgPath: `${path}\\jaggedy.svg` },
    { name: 'Link', svgPath: `${path}\\link.svg` },
    { name: 'Links HTML', svgPath: `${path}\\links.html` },
    { name: 'Move Tile', svgPath: `${path}\\move-tile.svg` },
    { name: 'New Cursor', svgPath: `${path}\\new-cursor.svg` },
    { name: 'New Placeholder', svgPath: `${path}\\new-placeholder.png` },
    { name: 'Output Editor View', svgPath: `${path}\\output-editor-view.svg` },
    { name: 'Placeholder Set', svgPath: `${path}\\placeholder-set.svg` },
    { name: 'Select Cursor', svgPath: `${path}\\select-cursor.svg` },
    { name: 'Selected', svgPath: `${path}\\selected.svg` },
    { name: 'Selection Cutout', svgPath: `${path}\\selection-cutout.svg` },
    { name: 'SVG Icons', svgPath: `${path}\\svg-icons.svg` },
    { name: 'Tile Editor Icon', svgPath: `${path}\\tile-editor-icon.svg` },
    { name: 'Tile Icons Background', svgPath: `${path}\\tile-icons-background.svg` },
    { name: 'Top Align', svgPath: `${path}\\top-align.svg` },
    { name: 'Visit Website', svgPath: `${path}\\visit-website.svg` },
    { name: 'Wavy Borders', svgPath: `${path}\\wavyborders.svg` }
  ]

