// auto-generated by scripts/prepare.ts
// public module keys for diamondcoreprocessor.com/hello-world
// do not edit manually

export const HelloWorldModule = 'diamondcoreprocessor.com/hello-world'
export const helloWorld = 'diamondcoreprocessor.com/hello-world/hw-service'
export const HelloWorldKeys = { helloWorld } as const
