// presentation/fonts/package-fonts.ts — GENERATED by scripts/package-fonts.mjs.
// Do not edit: rerun the script after scripts/fetch-fonts.cjs changes a face.
//
// The faces this package renders that the minimal host does not ship. The
// build signs each file and names it, with these descriptors, in the root
// layer's `resources` (scripts/build-module.ts); fonts.boot.drone.ts reads
// them from there and declares a face only where the page has none for its
// family and style. No signature lives in source.

export type PackageFont = {
  family: string
  style: string
  weight: string
  display: string
  unicodeRange: string
  file: string
}

export const PACKAGE_FONTS: readonly PackageFont[] = [
  {
    family: 'Source Serif 4',
    style: 'italic',
    weight: '400 600',
    display: 'swap',
    unicodeRange: 'U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF',
    file: 'source-serif-latin-ext.woff2'
  },
  {
    family: 'Source Serif 4',
    style: 'italic',
    weight: '400 600',
    display: 'swap',
    unicodeRange: 'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
    file: 'source-serif-latin.woff2'
  },
  {
    family: 'Material Symbols Outlined',
    style: 'normal',
    weight: '100 700',
    display: 'block',
    unicodeRange: '',
    file: 'material-symbols-all.woff2'
  }
]
