import { AfterViewInit, Component, effect, HostBinding, signal } from '@angular/core';
import { type Bee, EffectBus, hypercomb } from '@hypercomb/core';
import {
  DEFAULT_HEX_ORIENTATION,
  type HexOrientation,
} from '@hypercomb/essentials/preferences/settings';
import { RouterOutlet } from '@angular/router';
import { awaitFirstTilePaint } from '@hypercomb/shared/core/first-tile-paint';
import { isTransientMode } from '@hypercomb/shared/core/view-mode.service';
import { CommandLineComponent } from '@hypercomb/shared/ui/command-line/command-line.component';
import { ControlsBarComponent } from '@hypercomb/shared/ui/controls-bar/controls-bar.component';
import { EditActionsComponent } from '@hypercomb/shared/ui/edit-actions/edit-actions.component';
import { MeshHeaderComponent } from '@hypercomb/shared/ui/mesh-header/mesh-header.component';
import { ShellSurfacesComponent } from '@hypercomb/shared/ui/shell-surfaces/shell-surfaces.component';
import { SyncIndicatorComponent } from '@hypercomb/shared/ui/sync-indicator/sync-indicator.component';
import { UpgradeIndicatorComponent } from '@hypercomb/shared/ui/upgrade-indicator/upgrade-indicator.component';

// One import boots the full essentials module graph — every drone, queen,
// worker, input, and view self-registers in window.ioc.
// The barrel is regenerated by scripts/prepare.ts so new modules pick up
// automatically.
// This is a development-only source barrel. Use the workspace-relative path:
// package `exports` intentionally exposes the built library only, and relying
// on a cached TS path alias made watcher rebuilds fail whenever this generated
// source file was briefly refreshed.
import '../../../hypercomb-essentials/src/side-effects'

// Only these pulse-driven bees are allowed to run before the first settled
// tile frame. Settings/Axial/Layout are constructor-registered services with
// no pulse method; they are already available when these three start.
const RENDER_FIRST_KEYS = new Set([
  '@diamondcoreprocessor.com/PixiHostWorker',
  '@diamondcoreprocessor.com/ShowCellDrone',
  '@diamondcoreprocessor.com/BackgroundDrone',
])

@Component({
  selector: 'app-root',
  imports: [ControlsBarComponent, EditActionsComponent, MeshHeaderComponent, RouterOutlet, CommandLineComponent, ShellSurfacesComponent, SyncIndicatorComponent, UpgradeIndicatorComponent],
  styleUrls: ['./app.scss'] as any,
  templateUrl: './app.html'
})
export class App implements AfterViewInit {
  protected readonly title = signal('hypercomb-dev');
  readonly moveMode = signal(false);
  // Empty-layer swarm watermark — set when show-cell reports the current
  // public/swarm location has zero tiles.
  readonly swarmEmpty = signal(false);

  @HostBinding('class.move-mode')
  get moveModeClass() { return this.moveMode(); }

  @HostBinding('class.swarm-empty')
  get swarmEmptyClass() { return this.swarmEmpty(); }

  // ViewMode: 'hexagons' | 'website' | (any string). Mutually exclusive
  // rendering surface — drones gate on viewMode.is(name). Pixi canvas
  // hides via app.html [style.display] when not 'hexagons'.
  protected readonly viewMode = signal<string>('hexagons')

  @HostBinding('class.view-website')
  get viewWebsiteClass() { return this.viewMode() === 'website'; }

  // Always boots false — REFRESH → PRIVATE (the constructor force-writes
  // the flag off before bee startup; membership never survives a reload).
  public readonly meshPublic = signal(false);
  public readonly inputOpen = signal(false);
  public readonly viewActive = signal(false);
  public readonly orientation = signal<HexOrientation>(
    (localStorage.getItem('hc:hex-orientation') as HexOrientation) || DEFAULT_HEX_ORIENTATION
  );

  constructor() {
    // REFRESH → PRIVATE. Force swarm membership off FIRST, synchronously,
    // so every live localStorage sampler (nostr-mesh gate, swarm broadcast,
    // show-cell privacy reads) sees solo from the first moment of this
    // session. Parity with hypercomb-web's core-adapter module-scope write.
    try { localStorage.setItem('hc:mesh-public', 'false') } catch { /* no storage — default is off anyway */ }

    // Parity with hypercomb-web (app.ts): swallow the benign "ResizeObserver
    // loop completed with undelivered notifications" warning. It fires on
    // routine layout frames; without this it surfaces as a red ERROR AND runs
    // Angular's global ErrorHandler every time — a per-frame cost on dev that
    // makes the whole app feel sluggish. stopImmediatePropagation before
    // Angular's window 'error' listener sees it.
    window.addEventListener('error', e => {
      if ((e as ErrorEvent).message?.includes('ResizeObserver loop')) {
        e.stopImmediatePropagation()
      }
    })

    EffectBus.on<{ public: boolean }>('mesh:public-changed', ({ public: pub }) => {
      this.meshPublic.set(pub)
    })

    EffectBus.on<{ active: boolean }>('view:active', ({ active }) => {
      this.viewActive.set(active)
    })

    EffectBus.on<{ active: boolean }>('move:mode', ({ active }) => {
      this.moveMode.set(active)
    })

    EffectBus.on<{ active: boolean }>('swarm:empty-layer', ({ active }) => {
      this.swarmEmpty.set(active)
    })

    EffectBus.on<{ flat: boolean }>('render:set-orientation', ({ flat }) => {
      this.orientation.set(flat ? 'flat-top' : 'point-top')
    })

    // Development imports the startup behavior graph directly. Non-critical
    // lanes are generated into a separate chunk and warm only after the hive
    // has completed its first render, matching production's lazy posture.
    let preloadStarted = false
    EffectBus.on<{ count?: number; settled?: boolean }>('render:cell-count', ({ count, settled }) => {
      if (preloadStarted || (!(Number(count) > 0) && settled !== true)) return
      preloadStarted = true
      void import('../../../hypercomb-essentials/src/preload-effects')
        .then(({ preloadEffects }) => preloadEffects())
        .catch(error => console.warn('[app] post-render preload failed', error))
    })

    // Mobile command-line reveal: long-press on empty canvas (or controls
    // bar toggle) emits this; the header-bar must un-hide so the
    // command-line inside it becomes visible.
    EffectBus.on<{ visible: boolean; mobile: boolean }>('mobile:input-visible', ({ visible, mobile }) => {
      this.inputOpen.set(mobile && visible)
    })

    // ViewMode subscription — drives Pixi-canvas visibility via app.html
    // and the body class for global CSS. Self-registered in shared/core.
    const wireViewMode = (svc: { mode: string } & EventTarget): void => {
      this.viewMode.set(svc.mode)
      svc.addEventListener('change', () => this.viewMode.set(svc.mode))
    }
    const ioc = (window as unknown as { ioc?: { get: <T>(k: string) => T | undefined; whenReady: <T>(k: string, cb: (v: T) => void) => void } }).ioc
    if (ioc) {
      const now = ioc.get<{ mode: string } & EventTarget>('@hypercomb.social/ViewMode')
      if (now) wireViewMode(now)
      else ioc.whenReady<{ mode: string } & EventTarget>('@hypercomb.social/ViewMode', wireViewMode)
    }

    effect(() => {
      const m = this.viewMode()
      // Drop EVERY previous hc-view-* class (modes are open-ended; the old
      // two-name remove left stale classes behind when switching between
      // non-website views), then mark the current mode — plus the generic
      // `hc-view-covered` for any full-surface view, which is what the
      // canvas-suppression rule in styles.scss keys on. With the canvas
      // neutralised under every takeover view, a view-to-view navigation
      // exposes the themed body between surfaces, never a flash of tiles.
      for (const c of [...document.body.classList]) {
        if (c.startsWith('hc-view-')) document.body.classList.remove(c)
      }
      document.body.classList.add(`hc-view-${m}`)
      if (isTransientMode(m)) document.body.classList.add('hc-view-covered')
    })

    // ─── Return to the hive on adopt complete ──────────────────────────
    // After a successful branch adoption (broker.adopt walked the peer's
    // subtree → adopt:done fires), bring the participant back to the
    // tile-grid view at their current location. The adopted tiles
    // render there with their newly-fetched resources. Code items stay
    // off until the participant explicitly toggles them on (which fires
    // the trust prompt in DCP for non-community sources, per
    // home.component.onToggle).
    //
    // "Go back to the hive" semantics: the shell makes sure viewMode is
    // 'hexagons' (any non-tile view from before adopt is dismissed) and
    // emits 'nav:to-hive' so any other listener (toasts, banners, future
    // routing) can react. Idempotent — already on hexagons = no-op.
    // `silent` walks (pre-consent code inspection, features-panel downloads)
    // are background work — they must never yank the view.
    EffectBus.on<{ silent?: boolean }>('adopt:done', (p) => {
      if (p?.silent) return
      this.viewMode.set('hexagons')
      EffectBus.emit('nav:to-hive', { reason: 'adopt-complete' })
    })

    // Runtime already initialized by main.ts — go straight to bee startup.
    //
    // REFRESH → PRIVATE, dev exactly like production: the constructor
    // force-wrote `hc:mesh-public` off, and here the mesh network starts
    // disconnected to match. (The old dev-only default-ON is retired.)
    // Joining stays a one-gesture act — the dev relay (ws://localhost:7777)
    // is still in the relay-list defaults (loadRelays in
    // nostr-mesh.drone.ts), so a join needs zero extra setup.
    queueMicrotask(() => {
      const mesh = get('@diamondcoreprocessor.com/NostrMeshDrone') as any
      mesh?.setNetworkEnabled?.(false, true)
      void this.startRegisteredBees()
    })
  }

  ngAfterViewInit(): void {
  }

  public toggleOrientation = (): void => {
    const next: HexOrientation = this.orientation() === 'point-top' ? 'flat-top' : 'point-top'
    this.orientation.set(next)
    localStorage.setItem('hc:hex-orientation', next)
    EffectBus.emit('render:set-orientation', { flat: next === 'flat-top' })
  }

  public toggleMesh = (): void => {
    const mesh = get('@diamondcoreprocessor.com/NostrMeshDrone') as any;

    const next = !this.meshPublic();
    this.meshPublic.set(next);
    localStorage.setItem('hc:mesh-public', String(next))
    mesh?.setNetworkEnabled?.(next, true);
    EffectBus.emit('mesh:public-changed', { public: next })
  }

  private readonly startRegisteredBees = async (): Promise<void> => {
    // Subscribe before pulsing: PixiHostWorker + ShowCellDrone can settle the
    // first layer as soon as their pulses/host-ready hooks run. The processor's
    // resolver is ScriptPreloader, whose first find walks every bee/dependency
    // file in OPFS; starting that walk first stretched a trivial explorerDir()
    // read from single-digit milliseconds to ~900ms on a cold profile.
    const lineage = get('@hypercomb.social/Lineage') as { explorerLabel?: () => string } | undefined
    const firstTilePaint = awaitFirstTilePaint(String(lineage?.explorerLabel?.() ?? '/'))
    const entries = list()
      .map(key => ({ key, bee: get(key) }))
      .filter((entry): entry is { key: string; bee: Bee } =>
        !!entry.bee && typeof (entry.bee as Bee).pulse === 'function')
    const values = entries.map(entry => entry.bee)
    const renderFirst = entries.filter(entry => RENDER_FIRST_KEYS.has(entry.key))
    const afterPaint = entries.filter(entry => !RENDER_FIRST_KEYS.has(entry.key))

    // Every dev bee is already in the Angular bundle through generated
    // side-effects. Tell the resolver before first paint so BootstrapHistory
    // cannot launch a duplicate signature/OPFS module walk when its render
    // barrier opens.
    const preloader = get('@hypercomb.social/ScriptPreloader') as any
    preloader?.useRegisteredBees?.(values)

    // The renderer gets exclusive startup ownership. The previous full-array
    // pulse started every network/history/assistant bee alongside explorerDir
    // and image reads, so a cold current layer queued behind unrelated work.
    await Promise.allSettled(
      renderFirst.map(({ key, bee }) => bee.pulse('').catch(error =>
        console.warn('[app] failed to start render bee', key, error)
      ))
    )
    ;(window as any).__hcBoot?.(`dev render-first bees pulsed (${renderFirst.length})`)

    // Rendering owns startup. Only after the matching layer has published a
    // final geometry/empty verdict may the processor resolve and pulse the
    // wider installed behavior graph.
    await firstTilePaint
    await new hypercomb().act('')
    ;(window as any).__hcBoot?.('dev first layer settled; background bees starting')

    // Everything else begins only after the tile buffer has reached its final
    // geometry/empty verdict. Detached so startup UI and the first navigation
    // never await the background cohort.
    void Promise.allSettled(
      afterPaint.map(({ key, bee }) => bee.pulse('').catch(error =>
        console.warn('[app] failed to start background bee', key, error)
      ))
    ).then(() => {
      ;(window as any).__hcBoot?.(`dev background bees pulsed (${afterPaint.length})`)
    })

    // Dev mode: bees are imported directly, not through ScriptPreloader.
    // Set resourceCount so the command line unlocks.
    preloader?.setResourceCount?.(values.length)

    // restore persisted orientation
    if (this.orientation() === 'flat-top') {
      EffectBus.emit('render:set-orientation', { flat: true })
    }

    // broadcast initial mesh state so drones can react
    EffectBus.emit('mesh:public-changed', { public: this.meshPublic() })
  }
}
