import { AfterViewInit, Component, HostBinding, signal } from '@angular/core';
import { type Bee, EffectBus } from '@hypercomb/core';
import type { HexOrientation } from '@hypercomb/essentials/diamondcoreprocessor.com/preferences/settings';
import { RouterOutlet } from '@angular/router';
import { CommandLineComponent } from '@hypercomb/shared';
import { MeshHeaderComponent } from '@hypercomb/shared/ui';
import { TileEditorComponent } from '@hypercomb/shared/ui/tile-editor/tile-editor.component'
import { TrackPlayerComponent } from '@hypercomb/shared/ui/track-player/track-player.component'
import { ControlsBarComponent, ShortcutSheetComponent, CommandPaletteComponent, ActivityLogComponent, SelectionContextMenuComponent, HistoryViewerComponent, AtomizerBarComponent, AtomizerSidebarComponent, ConfirmDialogComponent, ToastComponent, InstructionOverlayComponent, DocsOverlayComponent, NotesStripComponent, NotesViewerComponent } from '@hypercomb/shared/ui';
import { FormatPainterComponent } from '@hypercomb/shared/ui/format-painter/format-painter.component'
import { PortalOverlayComponent } from '@hypercomb/shared/ui/portal/portal-overlay.component'
import { SensitivityBarComponent } from '@hypercomb/shared/ui/sensitivity-bar/sensitivity-bar.component'
import { YoutubeViewerComponent } from '@hypercomb/shared/ui/youtube-viewer/youtube-viewer.component'
import '@hypercomb/shared/ui/command-line/command-line.atomizer'

// One import boots the full essentials module graph — every drone, queen,
// worker, input, view, and atomizer self-registers in window.ioc.
// The barrel is regenerated by scripts/prepare.ts so new modules pick up
// automatically.
import '@hypercomb/essentials/side-effects'

@Component({
  selector: 'app-root',
  imports: [ControlsBarComponent, MeshHeaderComponent, RouterOutlet, CommandLineComponent, TileEditorComponent, ShortcutSheetComponent, CommandPaletteComponent, PortalOverlayComponent, ActivityLogComponent, SensitivityBarComponent, SelectionContextMenuComponent, HistoryViewerComponent, FormatPainterComponent, YoutubeViewerComponent, AtomizerBarComponent, AtomizerSidebarComponent, ConfirmDialogComponent, ToastComponent, InstructionOverlayComponent, DocsOverlayComponent, NotesStripComponent, NotesViewerComponent, TrackPlayerComponent],
  styleUrls: ['./app.scss'] as any,
  templateUrl: './app.html'
})
export class App implements AfterViewInit {
  protected readonly title = signal('hypercomb-dev');
  readonly clipboardMode = signal(false);
  readonly moveMode = signal(false);
  readonly playerOpen = signal(false);

  dismissPlayer(): void {
    this.playerOpen.set(false);
    try { localStorage.setItem('hc:player-dismissed', 'true') } catch { /* storage unavailable */ }
  }

  @HostBinding('class.clipboard-mode')
  get clipboardModeClass() { return this.clipboardMode(); }

  @HostBinding('class.move-mode')
  get moveModeClass() { return this.moveMode(); }

  public readonly meshPublic = signal(
    localStorage.getItem('hc:mesh-public') === 'true' ? true
    : false // default: solo mode
  );
  public readonly secretOpen = signal(false);
  public readonly inputOpen = signal(false);
  public readonly viewActive = signal(false);
  public readonly orientation = signal<HexOrientation>(
    (localStorage.getItem('hc:hex-orientation') as HexOrientation) || 'point-top'
  );

  constructor() {
    EffectBus.on<{ public: boolean }>('mesh:public-changed', ({ public: pub }) => {
      this.meshPublic.set(pub)
    })

    EffectBus.on<{ active: boolean }>('view:active', ({ active }) => {
      this.viewActive.set(active)
    })

    EffectBus.on<{ active: boolean }>('clipboard:view', ({ active }) => {
      this.clipboardMode.set(active)
    })

    EffectBus.on<{ active: boolean }>('move:mode', ({ active }) => {
      this.moveMode.set(active)
    })

    // Mobile command-line reveal: long-press on empty canvas (or controls
    // bar toggle) emits this; the header-bar must un-hide so the
    // command-line inside it becomes visible.
    EffectBus.on<{ visible: boolean; mobile: boolean }>('mobile:input-visible', ({ visible, mobile }) => {
      this.inputOpen.set(mobile && visible)
    })

    // Re-open the track player when /player queen is invoked
    EffectBus.on('player:open', () => {
      this.playerOpen.set(true)
    })

    // Runtime already initialized by main.ts — go straight to bee startup
    queueMicrotask(() => {
      if (localStorage.getItem('hc:mesh-public') === null) {
        localStorage.setItem('hc:mesh-public', 'false')
      }
      const stored = localStorage.getItem('hc:mesh-public')
      if (stored !== null) {
        const mesh = get('@diamondcoreprocessor.com/NostrMeshDrone') as any
        mesh?.setNetworkEnabled?.(stored === 'true', true)
      }
      void this.startRegisteredBees()
    })
  }

  ngAfterViewInit(): void {
  }

  public toggleOrientation = (): void => {
    const next: HexOrientation = this.orientation() === 'point-top' ? 'flat-top' : 'point-top'
    this.orientation.set(next)
    localStorage.setItem('hc:hex-orientation', next)
    EffectBus.emit('render:set-orientation', { flat: next === 'flat-top' })
  }

  public toggleMesh = (): void => {
    const mesh = get('@diamondcoreprocessor.com/NostrMeshDrone') as any;

    const next = !this.meshPublic();
    this.meshPublic.set(next);
    localStorage.setItem('hc:mesh-public', String(next))
    mesh?.setNetworkEnabled?.(next, true);
    EffectBus.emit('mesh:public-changed', { public: next })
  }

  private readonly startRegisteredBees = async (): Promise<void> => {
    const values = list()
      .map(key => get(key))
      .filter((value): value is Bee => !!value && typeof (value as Bee).pulse === 'function')

    await Promise.allSettled(
      values.map(bee => bee.pulse('').catch(error =>
        console.warn('[app] failed to start bee', bee.constructor?.name, error)
      ))
    )

    window.dispatchEvent(new Event('synchronize'))

    // Dev mode: bees are imported directly, not through ScriptPreloader.
    // Set resourceCount so the command line unlocks.
    const preloader = get('@hypercomb.social/ScriptPreloader') as any
    preloader?.setResourceCount?.(values.length)

    // restore persisted orientation
    if (this.orientation() === 'flat-top') {
      EffectBus.emit('render:set-orientation', { flat: true })
    }

    // broadcast initial mesh state so drones can react
    EffectBus.emit('mesh:public-changed', { public: this.meshPublic() })
  }
}
