// auto-generated by scripts/prepare.ts
// ambient externals for diamondcoreprocessor.com
// do not edit manually

declare module '@diamondcoreprocessor.com/core/axial' {
  export { AxialCoordinate } from '../diamondcoreprocessor.com/core/axial/axial-coordinate'
  export { distance, AxialService } from '../diamondcoreprocessor.com/core/axial/axial-service'
}

declare module '@diamondcoreprocessor.com/core' {
  export { Settings } from '../diamondcoreprocessor.com/core/settings'
}

declare module '@diamondcoreprocessor.com/core/zoom' {
  export { ZoomArbiter } from '../diamondcoreprocessor.com/core/zoom/zoom-arbiter'
  export { ZoomState } from '../diamondcoreprocessor.com/core/zoom/zoom-state'
  export type { ZoomSnapshot } from '../diamondcoreprocessor.com/core/zoom/zoom-state'
}

declare module '@diamondcoreprocessor.com/hello-world' {
  export { helloWorld } from '../diamondcoreprocessor.com/hello-world/hw-service'
}

declare module '@diamondcoreprocessor.com/pixi' {
  export { HexLabelAtlas } from '../diamondcoreprocessor.com/pixi/hex-label.atlas'
  export type { LabelUV } from '../diamondcoreprocessor.com/pixi/hex-label.atlas'
  export { HexSdfTextureShader } from '../diamondcoreprocessor.com/pixi/hex-sdf.shader'
}

declare module '@diamondcoreprocessor.com/screen' {
  export { ScreenService } from '../diamondcoreprocessor.com/screen/screen-service'
  export type { ScreenSnapshot } from '../diamondcoreprocessor.com/screen/screen-service'
  export { ScreenState } from '../diamondcoreprocessor.com/screen/screen-state'
}

declare module '@diamondcoreprocessor.com/settings' {
  export { ZoomSettings } from '../diamondcoreprocessor.com/settings/zoom-settings'
  export type { ZoomSettingsType } from '../diamondcoreprocessor.com/settings/zoom-settings'
}

