// AUTO-GENERATED by scripts/prepare.ts
// ambient externals for diamondcoreprocessor.com
// DO NOT EDIT MANUALLY

declare module '@diamondcoreprocessor.com/core/axial' {
  export { AxialCoordinate } from '../diamondcoreprocessor.com/core/axial/axial-coordinate'
  export { distance, AxialService } from '../diamondcoreprocessor.com/core/axial/axial-service'
}

declare module '@diamondcoreprocessor.com/core' {
  export { Settings } from '../diamondcoreprocessor.com/core/settings'
}

declare module '@diamondcoreprocessor.com/hello-world' {
  export { helloWorld } from '../diamondcoreprocessor.com/hello-world/hw-service'
}

declare module '@diamondcoreprocessor.com/pixi' {
  export { HexLabelAtlas } from '../diamondcoreprocessor.com/pixi/hex-label.atlas'
  export type { LabelUV } from '../diamondcoreprocessor.com/pixi/hex-label.atlas'
  export { HexSdfTextureShader } from '../diamondcoreprocessor.com/pixi/hex-sdf.shader'
}

declare module '@diamondcoreprocessor.com/screen' {
  export { ScreenService } from '../diamondcoreprocessor.com/screen/screen-service'
  export type { ScreenSnapshot } from '../diamondcoreprocessor.com/screen/screen-service'
  export { ScreenState } from '../diamondcoreprocessor.com/screen/screen-state'
}

